### PR TITLE
README minor fixes

### PR DESCRIPTION
**Pull request by tomgasaner**
Nothing special, just added/fixed controls specified in README

### CODE REVIEW

**Comment by kennylugo** [comment]
Is there a way to make ruby fighter faster?

**Comment by dmerrick** [comment]
+1

**Comment by kaievns** [comment]
nice one, thanks!

**Comment by kaievns** [comment]
@kennybatista @dmerrick absolutely, it just needs the animations engine to take a speed param. it's the initial implementation, so i just kinda picked whatevers for the animation speed, that's why it feels sluggish. but generally it spits out good 60-ish fps, so technically there is no limitation performance wise on the system side.

**Pull request merged**
